
const cheerio=require("cheerio");
function clean(v){return String(v||"").replace(/\s+/g," ").trim()}
function normPos(p){p=clean(p).toLowerCase().replace(/-/g," ");if(p.includes("goalkeeper"))return"GK";if(p.includes("centre back")||p.includes("center back"))return"CB";if(p.includes("left back"))return"LB";if(p.includes("right back"))return"RB";if(p.includes("defensive midfield"))return"DM";if(p.includes("central midfield"))return"CM";if(p.includes("attacking midfield"))return"AM";if(p.includes("left winger"))return"LW";if(p.includes("right winger"))return"RW";if(p.includes("centre forward")||p.includes("center forward")||p.includes("striker"))return"ST";return p}
function getText(html,label){let r=new RegExp(label+":[\\s\\S]{0,1000}?<span[^>]*>([^<]+)<\\/span>","i");return clean(html.match(r)?.[1]||"")}
function getTitle(html,label){let r=new RegExp(label+":[\\s\\S]{0,1500}?title=\\"([^\\"]+)\\"","i");return clean(html.match(r)?.[1]||"")}
function height(text){let m=clean(text).replace(",",".").match(/([0-9]+(?:\.[0-9]+)?)/);if(!m)return"";let n=Number(m[1]);return n<3?String(Math.round(n*100)):String(Math.round(n))}
async function fetchHtml(url){let res=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 Chrome/124 Safari/537.36","Accept-Language":"en-US,en;q=0.9"}});let html=await res.text();if(!res.ok||html.length<1000||/Access denied|captcha|blocked/i.test(html))throw new Error("Transfermarkt blokladı və ya cavab vermədi");return html}
module.exports=async(req,res)=>{res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Methods","POST,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type");if(req.method==="OPTIONS")return res.status(200).end();if(req.method!=="POST")return res.status(405).json({error:"Only POST"});try{let{url}=req.body||{};if(!url||!String(url).includes("transfermarkt"))return res.status(400).json({error:"Transfermarkt linki düzgün deyil"});let html=await fetchHtml(url),$=cheerio.load(html);let name=clean($("h1.data-header__headline-wrapper").first().text()).replace(/^#\d+\s*/,"");if(!name)name=clean($("meta[property='og:title']").attr("content")).replace(/- Player profile.*$/i,"").replace(/\| Transfermarkt.*$/i,"");let dob=getText(html,"Date of birth/Age"),age=dob.match(/\((\d+)\)/)?.[1]||"",positionFull=getText(html,"Position");let profile={name,age,dateOfBirth:dob,country:getTitle(html,"Citizenship")||getText(html,"Citizenship"),club:getTitle(html,"Current club")||getText(html,"Current club"),position:normPos(positionFull),positionFull,foot:getText(html,"Foot"),height:height(getText(html,"Height")),contractEnd:getText(html,"Contract expires"),joined:getText(html,"Joined"),agent:getTitle(html,"Player agent")||getText(html,"Player agent"),marketValue:clean($(".data-header__market-value-wrapper").first().text()),transfermarkt:url};profile.notes=["Transfermarkt açıq məlumat importu",profile.positionFull?`Transfermarkt mövqesi: ${profile.positionFull}`:"",profile.dateOfBirth?`Doğum tarixi: ${profile.dateOfBirth}`:"",profile.joined?`Kluba qoşulma: ${profile.joined}`:"",profile.agent?`Agent: ${profile.agent}`:"",profile.contractEnd?`Müqavilə sonu: ${profile.contractEnd}`:""].filter(Boolean).join("\\n");return res.status(200).json(profile)}catch(e){return res.status(500).json({error:"Transfermarkt import alınmadı",detail:String(e.message||e)})}}
