
import React,{useEffect,useMemo,useState}from"react";
import{Search,Plus,Trash2,Star,Download,Upload,LogIn,LogOut,Database,Link as LinkIcon,Save,Server}from"lucide-react";

const positions=["GK","RB","LB","CB","DM","CM","AM","RW","LW","ST"];
const statuses=["İzlənilir","İzlənildi","İzlənilsin","Transfer tövsiyəsi","Uyğun deyil","Arxiv"];
const STORAGE_USERS="scouting_users_v1",STORAGE_SESSION="scouting_session_v1",STORAGE_PLAYERS="scouting_players_v1",STORAGE_BACKEND_URL="scouting_backend_url_v1";
const samplePlayers=[{id:1,name:"Nümunə Futbolçu",age:24,country:"Azərbaycan",club:"Nümunə FK",league:"Misli Premyer Liqası",position:"CM",foot:"Sağ",height:178,contractEnd:"2027-06-30",marketValue:"€350k",transfermarkt:"",minutes:1640,goals:3,assists:5,scoutTech:7,scoutTactic:8,scoutPhysical:7,scoutMental:8,potential:7,status:"İzlənilir",notes:"Pas keyfiyyəti yaxşıdır, temp altında qərarvermə izlənməlidir."}];

function scoreOf(p){const nums=[p.scoutTech,p.scoutTactic,p.scoutPhysical,p.scoutMental,p.potential].map(Number).filter(n=>!Number.isNaN(n));if(!nums.length)return 0;return Math.round((nums.reduce((a,b)=>a+b,0)/nums.length)*10)/10}
function loadJson(k,f){try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch{return f}}
function normalizePosition(t){const raw=String(t||"").trim(),v=raw.toLowerCase().replace(/-/g," ");if(["gk","goalkeeper"].includes(v))return"GK";if(v.includes("centre back")||v.includes("center back")||v==="cb")return"CB";if(v.includes("left back")||v==="lb")return"LB";if(v.includes("right back")||v==="rb")return"RB";if(v.includes("defensive midfield")||v==="dm")return"DM";if(v.includes("central midfield")||v.includes("centre midfield")||v==="cm")return"CM";if(v.includes("attacking midfield")||v==="am")return"AM";if(v.includes("left winger")||v==="lw")return"LW";if(v.includes("right winger")||v==="rw")return"RW";if(v.includes("striker")||v.includes("centre forward")||v.includes("center forward")||v==="st")return"ST";return raw||"CM"}
function emptyForm(){return{name:"",age:"",dateOfBirth:"",country:"",placeOfBirth:"",club:"",league:"",position:"CM",positionFull:"",foot:"Sağ",height:"",joined:"",contractEnd:"",marketValue:"",agent:"",nationalTeam:"",appearances:"",minutes:"",goals:"",assists:"",yellowCards:"",redCards:"",transfermarkt:"",scoutTech:5,scoutTactic:5,scoutPhysical:5,scoutMental:5,potential:5,status:"İzlənilir",notes:""}}
function mockTransfermarktImport(url){const slug=url.split("/profil/spieler/")[0].split("/").filter(Boolean).pop()||"";return{name:slug.split("-").filter(Boolean).map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(" ")||"Transfermarkt futbolçusu",transfermarkt:url,notes:"Backend tapılmadı: demo rejimdə yalnız ad linkdən təxmin edildi."}}
function normalizeTransfermarktData(data,url){const raw=data.position||data.positionFull||"",pos=normalizePosition(raw);return{name:data.name||data.fullName||"",transfermarkt:data.transfermarkt||url,age:data.age||"",dateOfBirth:data.dateOfBirth||"",country:data.country||data.citizenship||"",placeOfBirth:data.placeOfBirth||"",club:data.club||"",league:data.league||"",joined:data.joined||"",position:pos,positionFull:raw,foot:data.foot||"Sağ",height:data.height||data.heightCm||"",marketValue:data.marketValue||"",contractEnd:data.contractEnd||"",agent:data.agent||"",nationalTeam:data.nationalTeam||"",appearances:data.appearances||data.games||"",minutes:data.minutes||"",goals:data.goals||"",assists:data.assists||"",yellowCards:data.yellowCards||"",redCards:data.redCards||"",transferHistory:Array.isArray(data.transferHistory)?data.transferHistory:[],careerStats:Array.isArray(data.careerStats)?data.careerStats:[],notes:[data.notes||"Transfermarkt backend import ilə əlavə edildi.",raw&&raw!==pos?`Transfermarkt mövqesi: ${raw}`:"",data.dateOfBirth?`Doğum tarixi: ${data.dateOfBirth}`:"",data.joined?`Kluba qoşulma: ${data.joined}`:"",data.agent?`Agent: ${data.agent}`:""].filter(Boolean).join(String.fromCharCode(10))}}

export default function App(){
const[users,setUsers]=useState(()=>loadJson(STORAGE_USERS,[{email:"admin@scout.local",password:"12345",name:"Scout Admin"}]));
const[session,setSession]=useState(()=>loadJson(STORAGE_SESSION,null));
const[players,setPlayers]=useState(()=>loadJson(STORAGE_PLAYERS,samplePlayers));
const[query,setQuery]=useState(""),[position,setPosition]=useState("Hamısı"),[status,setStatus]=useState("Hamısı"),[countryFilter,setCountryFilter]=useState("Hamısı"),[clubFilter,setClubFilter]=useState("Hamısı"),[minAge,setMinAge]=useState(""),[maxAge,setMaxAge]=useState(""),[minRating,setMinRating]=useState("");
const[selectedId,setSelectedId]=useState(players[0]?.id||null),[form,setForm]=useState(emptyForm()),[authForm,setAuthForm]=useState({email:"admin@scout.local",password:"12345",name:""}),[authMode,setAuthMode]=useState("login"),[tmUrl,setTmUrl]=useState(""),[backendUrl,setBackendUrl]=useState(()=>localStorage.getItem(STORAGE_BACKEND_URL)||"http://localhost:3001/api/transfermarkt"),[isImporting,setIsImporting]=useState(false),[message,setMessage]=useState("");

useEffect(()=>localStorage.setItem(STORAGE_USERS,JSON.stringify(users)),[users]);
useEffect(()=>localStorage.setItem(STORAGE_SESSION,JSON.stringify(session)),[session]);
useEffect(()=>localStorage.setItem(STORAGE_PLAYERS,JSON.stringify(players)),[players]);
useEffect(()=>localStorage.setItem(STORAGE_BACKEND_URL,backendUrl),[backendUrl]);

const countryOptions=useMemo(()=>["Hamısı",...Array.from(new Set(players.map(p=>p.country).filter(Boolean))).sort()],[players]);
const clubOptions=useMemo(()=>["Hamısı",...Array.from(new Set(players.map(p=>p.club).filter(Boolean))).sort()],[players]);
const filtered=useMemo(()=>players.filter(p=>position==="Hamısı"||normalizePosition(p.position)===position).filter(p=>status==="Hamısı"||p.status===status).filter(p=>countryFilter==="Hamısı"||p.country===countryFilter).filter(p=>clubFilter==="Hamısı"||p.club===clubFilter).filter(p=>!minAge||Number(p.age)>=Number(minAge)).filter(p=>!maxAge||Number(p.age)<=Number(maxAge)).filter(p=>!minRating||scoreOf(p)>=Number(minRating)).filter(p=>[p.name,p.club,p.country,p.position,p.notes].join(" ").toLowerCase().includes(query.toLowerCase())).sort((a,b)=>scoreOf(b)-scoreOf(a)),[players,query,position,status,countryFilter,clubFilter,minAge,maxAge,minRating]);
const selected=players.find(p=>p.id===selectedId)||filtered[0]||players[0];

function loginOrRegister(){if(authMode==="register"){if(!authForm.email||!authForm.password)return setMessage("Email və şifrə yaz.");if(users.some(u=>u.email===authForm.email))return setMessage("Bu email artıq mövcuddur.");const u={...authForm,name:authForm.name||authForm.email};setUsers(p=>[...p,u]);setSession({email:u.email,name:u.name});return}const u=users.find(u=>u.email===authForm.email&&u.password===authForm.password);if(!u)return setMessage("Email və ya şifrə yanlışdır.");setSession({email:u.email,name:u.name})}
function addPlayer(){if(!form.name.trim())return setMessage("Futbolçu adı yazılmalıdır.");const n={...form,id:Date.now(),createdBy:session?.email};setPlayers(p=>[n,...p]);setSelectedId(n.id);setForm(emptyForm());setMessage("Futbolçu bazaya əlavə edildi.")}
async function importTransfermarkt(){if(!tmUrl.includes("transfermarkt"))return setMessage("Transfermarkt linki daxil et.");setIsImporting(true);setMessage("Transfermarkt məlumatları oxunur...");try{const r=await fetch(backendUrl,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:tmUrl})});if(!r.ok)throw new Error("Backend cavab vermədi");const d=await r.json();setForm(p=>({...p,...normalizeTransfermarktData(d,tmUrl)}));setMessage("Transfermarkt məlumatları backend-dən gətirildi və forma dolduruldu.")}catch{setForm(p=>({...p,...mockTransfermarktImport(tmUrl)}));setMessage("Backend tapılmadı və ya cavab vermədi. Demo rejim işlədi.")}finally{setIsImporting(false)}}
function removePlayer(id){setPlayers(p=>p.filter(x=>x.id!==id))}
function updatePlayerStatus(id,s){setPlayers(p=>p.map(x=>x.id===id?{...x,status:s}:x));setMessage("Status yeniləndi.")}
function updatePlayerNotes(id,n){setPlayers(p=>p.map(x=>x.id===id?{...x,notes:n}:x))}
function updatePlayerField(id,f,v){setPlayers(p=>p.map(x=>x.id===id?{...x,[f]:v}:x))}
function exportJson(){const b=new Blob([JSON.stringify(players,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="scouting-baza.json";a.click();URL.revokeObjectURL(u)}
function importJson(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(String(reader.result));if(Array.isArray(d)){setPlayers(d);setMessage("Baza import edildi.")}}catch{setMessage("Import alınmadı.")}};reader.readAsText(file)}

if(!session)return <div className="min-h-screen bg-slate-950 p-4 text-slate-900"><div className="mx-auto flex min-h-screen max-w-md items-center"><div className="w-full rounded-3xl bg-white p-6 shadow-xl"><div className="mb-5 flex items-center gap-3"><div className="rounded-2xl bg-slate-900 p-3 text-white"><Database size={24}/></div><div><h1 className="text-2xl font-bold">Scout Login</h1><p className="text-sm text-slate-500">Demo giriş: admin@scout.local / 12345</p></div></div><div className="space-y-3">{authMode==="register"&&<input placeholder="Ad" value={authForm.name} onChange={e=>setAuthForm({...authForm,name:e.target.value})} className="w-full rounded-xl border px-3 py-2"/>}<input placeholder="Email" value={authForm.email} onChange={e=>setAuthForm({...authForm,email:e.target.value})} className="w-full rounded-xl border px-3 py-2"/><input placeholder="Şifrə" type="password" value={authForm.password} onChange={e=>setAuthForm({...authForm,password:e.target.value})} className="w-full rounded-xl border px-3 py-2"/>{message&&<p className="text-sm text-red-600">{message}</p>}<button onClick={loginOrRegister} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 font-medium text-white"><LogIn size={18}/>{authMode==="login"?"Daxil ol":"Qeydiyyat"}</button><button onClick={()=>setAuthMode(authMode==="login"?"register":"login")} className="w-full text-sm text-slate-500">{authMode==="login"?"Yeni istifadəçi yarat":"Loginə qayıt"}</button></div></div></div></div>;

const fields=[["name","Ad soyad"],["age","Yaş"],["dateOfBirth","Doğum tarixi"],["country","Ölkə"],["placeOfBirth","Doğum yeri"],["club","Klub"],["league","Liqa"],["height","Boy"],["foot","Ayaq"],["joined","Kluba qoşulma"],["contractEnd","Müqavilə sonu"],["marketValue","Bazar dəyəri"],["agent","Agent"],["nationalTeam","Milli komanda"],["appearances","Oyun"],["minutes","Dəqiqə"],["goals","Qol"],["assists","Assist"],["yellowCards","Sarı kart"],["redCards","Qırmızı kart"],["transfermarkt","Transfermarkt link"]];

return <div className="min-h-screen bg-slate-50 p-4 text-slate-900"><div className="mx-auto max-w-7xl space-y-4">
<header className="flex flex-col gap-3 rounded-2xl bg-white p-5 shadow-sm md:flex-row md:items-center md:justify-between"><div><h1 className="text-2xl font-bold">Əsas Komanda Skautinq Bazası</h1><p className="text-sm text-slate-500">Transfermarkt import, filtrlər və skaut qeydləri.</p></div><div className="flex flex-wrap gap-2"><button onClick={exportJson} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-medium text-white"><Download size={16}/> Export</button><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-medium ring-1 ring-slate-200"><Upload size={16}/> Import<input type="file" accept="application/json" className="hidden" onChange={importJson}/></label><button onClick={()=>setSession(null)} className="inline-flex items-center gap-2 rounded-xl bg-red-50 px-4 py-2 text-sm font-medium text-red-700"><LogOut size={16}/> Çıxış</button></div></header>
{message&&<div className="rounded-2xl bg-blue-50 p-3 text-sm text-blue-800">{message}</div>}
<section className="rounded-2xl bg-white p-3 shadow-sm"><div className="grid gap-2 lg:grid-cols-[1.2fr_2fr_auto] lg:items-end"><div><label className="mb-1 flex items-center gap-1 text-xs font-medium text-slate-500"><Server size={13}/> Backend URL</label><input value={backendUrl} onChange={e=>setBackendUrl(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"/></div><div><label className="mb-1 flex items-center gap-1 text-xs font-medium text-slate-500"><LinkIcon size={13}/> Transfermarkt linki</label><input value={tmUrl} onChange={e=>setTmUrl(e.target.value)} placeholder="https://www.transfermarkt.com/.../profil/spieler/..." className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"/></div><button disabled={isImporting} onClick={importTransfermarkt} className="inline-flex min-w-[145px] items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-60"><Save size={16}/>{isImporting?"Oxunur...":"Formaya gətir"}</button></div></section>

<section className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl bg-white p-4 shadow-sm lg:col-span-1"><h2 className="mb-3 flex items-center gap-2 text-lg font-semibold"><Plus size={18}/> Yeni futbolçu</h2><div className="grid grid-cols-2 gap-2">{fields.map(([k,l])=><input key={k} placeholder={l} value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"/>)}<select value={form.position} onChange={e=>setForm({...form,position:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2 text-sm">{positions.map(p=><option key={p}>{p}</option>)}</select><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2 text-sm">{statuses.map(s=><option key={s}>{s}</option>)}</select><textarea placeholder="Skaut qeydi" value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})} className="col-span-2 min-h-20 rounded-xl border border-slate-200 px-3 py-2 text-sm"/></div><div className="mt-3 grid grid-cols-5 gap-2 text-xs">{[["scoutTech","Tex"],["scoutTactic","Tak"],["scoutPhysical","Fiz"],["scoutMental","Men"],["potential","Pot"]].map(([k,l])=><label key={k} className="space-y-1">{l}<input type="number" min="1" max="10" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="w-full rounded-lg border border-slate-200 px-2 py-1"/></label>)}</div><button onClick={addPlayer} className="mt-4 w-full rounded-xl bg-emerald-600 px-4 py-2 font-medium text-white">Əlavə et</button></div>

<div className="rounded-2xl bg-white p-4 shadow-sm lg:col-span-2"><div className="mb-3 space-y-3"><div className="grid gap-2 md:grid-cols-3"><div className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Axtar..." className="w-full outline-none"/></div><select value={position} onChange={e=>setPosition(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2"><option>Hamısı</option>{positions.map(p=><option key={p}>{p}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2"><option>Hamısı</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="flex flex-wrap gap-2">{positions.map(p=><button key={p} onClick={()=>setPosition(p)} className={`rounded-xl px-3 py-1 text-sm font-medium ring-1 ring-slate-200 ${position===p?"bg-slate-900 text-white":"bg-white text-slate-700"}`}>{p}</button>)}<button onClick={()=>setPosition("Hamısı")} className="rounded-xl bg-slate-100 px-3 py-1 text-sm font-medium text-slate-700">Hamısı</button></div><div className="grid gap-2 md:grid-cols-5"><select value={countryFilter} onChange={e=>setCountryFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2">{countryOptions.map(c=><option key={c}>{c}</option>)}</select><select value={clubFilter} onChange={e=>setClubFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2">{clubOptions.map(c=><option key={c}>{c}</option>)}</select><input value={minAge} onChange={e=>setMinAge(e.target.value)} placeholder="Min yaş" type="number" className="rounded-xl border border-slate-200 px-3 py-2"/><input value={maxAge} onChange={e=>setMaxAge(e.target.value)} placeholder="Max yaş" type="number" className="rounded-xl border border-slate-200 px-3 py-2"/><input value={minRating} onChange={e=>setMinRating(e.target.value)} placeholder="Min reytinq (10)" type="number" className="rounded-xl border border-slate-200 px-3 py-2"/></div><div className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm text-slate-600"><span>Tapıldı: <b>{filtered.length}</b> futbolçu</span><button onClick={()=>{setQuery("");setPosition("Hamısı");setStatus("Hamısı");setCountryFilter("Hamısı");setClubFilter("Hamısı");setMinAge("");setMaxAge("");setMinRating("")}} className="font-medium text-slate-900">Filtrləri təmizlə</button></div></div>
<div className="overflow-auto rounded-xl border border-slate-100"><table className="w-full text-left text-sm"><thead className="bg-slate-100 text-slate-600"><tr><th className="p-3">Ad</th><th>Mövqe</th><th>Klub</th><th>Yaş</th><th>Status</th><th>Redaktə</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} onClick={()=>setSelectedId(p.id)} className="cursor-pointer border-t border-slate-100 hover:bg-slate-50"><td className="p-3 font-medium">{p.name}</td><td>{normalizePosition(p.position)}</td><td>{p.club}</td><td>{p.age}</td><td onClick={e=>e.stopPropagation()}><select value={p.status||"İzlənilir"} onChange={e=>updatePlayerStatus(p.id,e.target.value)} className="rounded-lg border border-slate-200 px-2 py-1 text-xs">{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td onClick={e=>e.stopPropagation()}><button onClick={()=>setSelectedId(p.id)} className="rounded-lg bg-slate-100 px-3 py-1 text-xs font-medium text-slate-700">Edit</button></td><td><button onClick={e=>{e.stopPropagation();removePlayer(p.id)}} className="rounded-lg p-2 hover:bg-red-50"><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></div></section>

{selected&&<section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between"><div><h2 className="text-xl font-bold">{selected.name}</h2><p className="text-slate-500">{normalizePosition(selected.position)} · {selected.club} · {selected.country}</p></div><div className="flex flex-wrap items-center gap-2"><select value={selected.status||"İzlənilir"} onChange={e=>updatePlayerStatus(selected.id,e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-medium">{statuses.map(s=><option key={s}>{s}</option>)}</select><div className="flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 font-semibold text-amber-700"><Star size={18}/> Reytinq: {scoreOf(selected)}/10</div></div></div><div className="mt-4 rounded-xl bg-slate-50 p-4"><div className="mb-3 text-sm font-semibold">Redaktə</div><div className="grid gap-2 md:grid-cols-5">{[["scoutTech","Texnika"],["scoutTactic","Taktika"],["scoutPhysical","Fiziki"],["scoutMental","Mental"],["potential","Potensial"]].map(([f,l])=><label key={f} className="text-xs text-slate-500">{l}<input type="number" min="1" max="10" value={selected[f]||5} onChange={e=>updatePlayerField(selected.id,f,e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold"/></label>)}</div></div><div className="mt-4 grid gap-3 md:grid-cols-4">{[["Yaş",selected.age],["Doğum tarixi",selected.dateOfBirth],["Liqa",selected.league],["Ayaq",selected.foot],["Boy",selected.height],["Kluba qoşulma",selected.joined],["Müqavilə",selected.contractEnd],["Bazar dəyəri",selected.marketValue],["Agent",selected.agent],["Milli komanda",selected.nationalTeam],["Oyun",selected.appearances],["Dəqiqə",selected.minutes],["Qol",selected.goals],["Assist",selected.assists],["Sarı kart",selected.yellowCards],["Qırmızı kart",selected.redCards]].map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">{k}</div><div className="font-semibold">{v||"—"}</div></div>)}</div>{Array.isArray(selected.transferHistory)&&selected.transferHistory.length>0&&<div className="mt-4 rounded-xl bg-slate-50 p-4"><div className="mb-2 text-sm font-semibold">Transfer tarixçəsi</div>{selected.transferHistory.slice(0,8).map((x,i)=><div key={i} className="text-sm text-slate-700">{x}</div>)}</div>}<div className="mt-4 rounded-xl bg-slate-50 p-4"><div className="mb-2 text-sm font-semibold">Skaut qeydi</div><textarea value={selected.notes||""} onChange={e=>updatePlayerNotes(selected.id,e.target.value)} placeholder="Skaut qeydlərini yaz..." className="min-h-[180px] w-full rounded-xl border border-slate-200 bg-white p-3 text-sm"/></div></section>}
</div></div>
}
